# Generated by Django 2.1.2 on 2018-11-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181112_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liststudents',
            name='FKIdCourse',
        ),
        migrations.RemoveField(
            model_name='liststudents',
            name='FKLicence',
        ),
        migrations.DeleteModel(
            name='ListStudents',
        ),
    ]
