# Generated by Django 2.1.2 on 2018-11-15 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181115_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStudents',
            fields=[
                ('IdListStudents', models.AutoField(primary_key=True, serialize=False)),
                ('FKIdCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('FKLicence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
