# Generated by Django 2.1.2 on 2018-11-15 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_liststudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistance',
            name='FKIdCourse',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistance',
            name='FKLicence',
            field=models.ForeignKey(limit_choices_to={'FKLicenceType': 8}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='Teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'FKLicenceType': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liststudents',
            name='FKLicence',
            field=models.ForeignKey(limit_choices_to={'FKLicenceType': 8}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
